env: development

logging:
  train:
    disable_default_loggers: true
    log_dir: ./logs/train/
    log_filename: trainlog.txt
    formatters:
      development:
        format: '{time:DD-MM-YYYY HH:mm:ss}:<red>[{level}]</red>:<cyan>{name}</cyan>:<cyan>{function}</cyan>:{line} - {message} - <green>[{elapsed}]</green>'
        backtrace: true
        diagnose: true
        enqueue: false
        level: INFO
  eval:
    disable_default_loggers: true
    log_dir: ./logs/eval/
    log_filename: evallog.txt
    formatters:
      development:
        format: '{time:DD-MM-YYYY HH:mm:ss}:<red>[{level}]</red>:<cyan>{name}</cyan>:<cyan>{function}</cyan>:{line} - {message} - <green>[{elapsed}]</green>'
        backtrace: true
        diagnose: true
        enqueue: true
        level: INFO

data:
  batch_size: 32
  image_size: 224
  image_depth: 3
  dataset_folder: "./"
  num_workers: 8
  shuffle: true
  use_random_horizontal_flip: true
  random_affine:
    degrees:
      - -30
      - 30
    translate:
      - 0.1
      - 0.3
    scale:
      - 0.1
      - 0.5
  color_jitter:
    brightness: 0.5
    hue: 0.25

model:
  model_save_folder: ./artifacts/train/
  model_save_freq: 10
  N_saved_model_to_keep: 10
  model_name: vit
  patch_size: 16
  transformer_depth: 12
  num_heads: 3
  patch_embedding_dim: 192
  mlp_ratio: 4
  projection_keys_dim: 192
  projection_values_dim: 192
  attn_dropout_prob: 0.1
  mlp_dropout_prob: 0.1

training:
  device: gpu
  load_checkpoint: true
  load_checkpoint_epoch: null #a specific checkpoint to load. Latest checkpoint will be loaded if null.
  start_epoch: 0
  end_epoch: 1000
  cosine_upper_bound_lr: 1.0e-4
  cosine_lower_bound_lr: 1.0e-6
  cosine_upper_bound_wd: 0.4
  cosine_lower_bound_wd: 0.04
  num_epochs_to_restart_lr: 10
  warmup_start_lr: 5.0e-5
  use_bfloat16: true
  use_neptune: true

























