env: development

logger:
  train:
    disable_default_loggers: true
    log_dir: ./logs/train/
    log_filename: trainlog.txt
    formatters:
      development:
        format: '{time:DD-MM-YYYY HH:mm:ss}:<red>[{level}]</red>:<cyan>{name}</cyan>:<cyan>{function}</cyan>:{line} - {message} - <green>[{elapsed}]</green>'
        backtrace: true
        diagnose: true
        enqueue: false
        level: INFO
  eval:
    disable_default_loggers: true
    log_dir: ./logs/eval/
    log_filename: evallog.txt
    formatters:
      development:
        format: '{time:DD-MM-YYYY HH:mm:ss}:<red>[{level}]</red>:<cyan>{name}</cyan>:<cyan>{function}</cyan>:{line} - {message} - <green>[{elapsed}]</green>'
        backtrace: true
        diagnose: true
        enqueue: true
        level: INFO

data:
  batch_size: 32
  image_size: 224
  image_depth: 3
  dataset_folder: "./"
  num_workers: 8
  shuffle: true
  use_random_horizontal_flip: true
  random_affine:
    degrees:
      - -30
      - 30
    translate:
      - 0.1
      - 0.3
    scale:
      - 0.1
      - 0.5
  color_jitter:
    brightness: 0.5
    hue: 0.25

